const DEFAULT_SALT_LENGTH = 12;
const DEFAULT_HASH_LENGTH = 16;
const DEFAULT_BUFFER_ENCODING: BufferEncoding = "hex";
const DEFAULT_HASH_SALT_SEPARATOR = ".";

export {
  DEFAULT_SALT_LENGTH,
  DEFAULT_HASH_LENGTH,
  DEFAULT_BUFFER_ENCODING,
  DEFAULT_HASH_SALT_SEPARATOR,
};
